name: Terraform fmt

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  Terraform_Fmt:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-fmt.yml@main
    with:
      terraform_version: '1.9.5'