name: Markdown Lint
on:
    pull_request:
      paths:
        - '**.md'
      branches:
        - '**'
    workflow_call:

jobs:
  Markdonw_Lint:
    uses: Coalfire-CF/Actions/.github/workflows/org-markdown-lint.yml@main